apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: person-service-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: This is a demo operator
  displayName: Simple Quarkus Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - quarkus.helm.chart
  links:
  - name: Person Service Operator
    url: https://person-service-operator.domain
  maintainers:
  - email: tberrey@redhat.com
    name: Thomas Berrey
  maturity: alpha
  provider:
    name: Thomas Berrey
  version: 0.0.0
