quay.io/tberrey/person-serviceapiVersion: charts.tberrey.org/v1alpha1
kind: PersonService
metadata:
  name: personservice-sample
spec:
  config:
    greeting: Hello from inside the operator!!!!
  deployment:
    image: quay.io/tberrey/person-service
    includeHealthChecks: false
    replicas: 1
    version: v1.0.0-test
  # Default values copied from <project_dir>/helm-charts/test-app/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 80
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  
  
